server:
  port: 8080

spring:
  profiles:
    active:
      - test
  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:ES;%8_gCf)e+*q[J(mM@#6Tp>k*Ft=/j5{q_8cD~;bu)n?7;Yz`d2(RbgpWS!._A[cszkq}(:/]2<@3pa[f,nHZ5m9Mr6xwS:/,H&U3A>Ds;[W}
  expiration: ${JWT_EXPIRATION:3600000}